
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg px-4">
    <a class="navbar-brand" href="index.html">
            <img src="assets/images/SkillSwap_logo.png" alt="Logo" />
          </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item"><a class="nav-link" href="index.php">Home</a></li>
        <li class="nav-item"><a class="nav-link" href="skills.php">All Skills</a></li>
        <li class="nav-item"><a class="nav-link" href="gallery.php">Gallery</a></li>
        <li class="nav-item"><a class="nav-link" href="add.php">Add Skill</a></li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control search-box" type="search" placeholder="Search skills..." aria-label="Search">
      </form>
    </div>
  </nav>